-- SQL Script Koreksi - Sesuai dengan Implementasi App.jsx
-- Copy & paste di SQL Editor di Supabase Console

-- 🔄 PERUBAHAN PENTING:
-- App.jsx Anda tidak menggunakan Supabase Authentication.
-- Validasi password dilakukan di FRONTEND (17jan2003).
-- Supabase hanya berfungsi sebagai CLOUD STORAGE untuk data portfolio.
-- Oleh karena itu, schema diubah untuk PUBLIC ACCESS (tanpa RLS user-specific).

-- 1. Bersihkan tabel lama (jika ada)
DROP TABLE IF EXISTS portfolios CASCADE;
DROP TABLE IF EXISTS portfolio_content CASCADE;

-- 2. Buat tabel untuk menyimpan data portfolio (kompatibel dengan App.jsx)
CREATE TABLE IF NOT EXISTS portfolio_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data JSONB NOT NULL, -- Kolom ini menyimpan SELURUH portfolio data (text, images, settings, etc)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Masukkan DATA AWAL (Row dengan ID = 1 HARUS ADA)
-- React App mencari data dengan ID = 1. Buat row ini terlebih dahulu.
INSERT INTO portfolio_content (id, data)
VALUES (
  1, 
  '{}'::jsonb -- Data kosong awal. Data ini akan otomatis tertimpa saat Anda klik SAVE pertama kali dari App
)
ON CONFLICT DO NOTHING; -- Jika sudah ada, jangan insert ulang

-- 4. Enable RLS (Row Level Security)
ALTER TABLE portfolio_content ENABLE ROW LEVEL SECURITY;

-- 5. Buat POLICY: Izinkan PUBLIC untuk READ & WRITE
-- KENAPA PUBLIC? Karena:
--   • Validasi password dilakukan di FRONTEND (App.jsx)
--   • Supabase hanya bertugas sebagai Cloud Storage
--   • Mode "Site Builder" memerlukan public access
-- KEAMANAN: Password hardcoded di frontend (17jan2003) + Supabase credentials di .env.local

CREATE POLICY "Allow Public Read"
  ON portfolio_content
  FOR SELECT
  USING (true); -- Siapa saja bisa baca

CREATE POLICY "Allow Public Insert"
  ON portfolio_content
  FOR INSERT
  WITH CHECK (true); -- Siapa saja bisa insert

CREATE POLICY "Allow Public Update"
  ON portfolio_content
  FOR UPDATE
  USING (true)
  WITH CHECK (true); -- Siapa saja bisa update

CREATE POLICY "Allow Public Delete"
  ON portfolio_content
  FOR DELETE
  USING (true); -- Siapa saja bisa delete

-- 6. CATATAN PENTING:
-- • Tabel portfolio_content hanya punya 1 row (ID = 1)
-- • Semua data portfolio disimpan dalam kolom 'data' (JSONB)
-- • Struktur JSONB match dengan DEFAULT_CONTENT di App.jsx:
--   {
--     theme: { primary, secondary, accent, bg, fonts: { title, body } },
--     socials: [ ... ],
--     decorations: [ ... ],
--     nav: { logoText, logoImage, menu: [ ... ] },
--     footer: { text, tagline },
--     sections: [ ... ]
--   }
-- • Saat App.jsx klik SAVE, data object lengkap dikirim dan replace row ID = 1
-- • Saat App.jsx load pertama kali, baca data dari ID = 1 dan set ke state
